// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxNM8kir9ELh_4vGvJaniw7XPf0em8vTs',
    appId: '1:696561570023:web:22275319772638d2e9d242',
    messagingSenderId: '696561570023',
    projectId: 'projectlogin-04',
    authDomain: 'projectlogin-04.firebaseapp.com',
    storageBucket: 'projectlogin-04.firebasestorage.app',
    measurementId: 'G-THP1XEBK79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSjFGpFPJjN8I1C5F-8N5Yhr623uo0j4E',
    appId: '1:696561570023:android:e3ccc0572c47eae8e9d242',
    messagingSenderId: '696561570023',
    projectId: 'projectlogin-04',
    storageBucket: 'projectlogin-04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOXLYuP_eWbquQrlCAlpivj_u7MzwSISo',
    appId: '1:696561570023:ios:8d538011afecd7a6e9d242',
    messagingSenderId: '696561570023',
    projectId: 'projectlogin-04',
    storageBucket: 'projectlogin-04.firebasestorage.app',
    iosBundleId: 'com.example.signup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOXLYuP_eWbquQrlCAlpivj_u7MzwSISo',
    appId: '1:696561570023:ios:8d538011afecd7a6e9d242',
    messagingSenderId: '696561570023',
    projectId: 'projectlogin-04',
    storageBucket: 'projectlogin-04.firebasestorage.app',
    iosBundleId: 'com.example.signup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxNM8kir9ELh_4vGvJaniw7XPf0em8vTs',
    appId: '1:696561570023:web:4ba6e5ac4eb299cce9d242',
    messagingSenderId: '696561570023',
    projectId: 'projectlogin-04',
    authDomain: 'projectlogin-04.firebaseapp.com',
    storageBucket: 'projectlogin-04.firebasestorage.app',
    measurementId: 'G-DCLX0XR3ED',
  );
}
